project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - blogs.qmd
    - blogs/VAE_derivation/VAE_derivation.qmd
    - blogs/DEL_Model/DEL_modelling_Part_1.qmd
    - blogs/DEL_Model/DEL_modelling_Part_2.qmd
  
website:
  navbar:
    title: "Avid Afzal"
    left:
      - href: index.qmd
        text: Home
      - href: blogs.qmd
        text: Blogs

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full
    main-container: "container-xxl"

editor: visual

